export type AreaStreetMapping = Record<string, string[]>;

export const areaStreetMapping: AreaStreetMapping = {
  Vrygrond: [
    "Apple Cl",
    "Apple Rd",
    "Berg Str",
    "Berry Cl",
    "Berry Rd",
    "Church Circ",
    "Classen Rd",
    "Darling Rd",
    "Dassie Cl",
    "Dassie Rd",
    "Davids Rd",
    "Dawn Rd",
    "Disa Cl",
    "Disa Rd",
    "Doring Cl",
    "Doring Rd",
    "Drury Cl",
    "Drury Rd",
    "Fredericks Cl",
    "Fredericks Rd",
    "Harmony Cl",
    "Harmony Rd",
    "Jappie Rd",
    "Jonathan Rd",
    "Mandla Rd",
    "Masakhane Rd",
    "Neville Riley Rd",
    "Orange Cl",
    "Orange Rd",
    "Peace Rd",
    "Peach Cl",
    "Peach Rd",
    "Philemon Rd",
    "Plum Str",
    "Thys Witbooi Cl",
    "Thys Witbooi Rd",
    "Trevor Siljeur Cl",
    "Trevor Siljeur Rd",
    "Vrygrond Ave",
    "Vuyo Cl",
    "Vuyo Rd",
  ],
  "Overcome Heights": [
    "7th Avenue",
    "Bree Str",
    "Errol Str",
    "Freedom Rd",
    "Ghetto",
    "Italyfield",
    "Kennedy Rd",
    "Liberty Rd",
    "Masakoni Rd",
    "Mercy Rd",
    "Mountain Rd",
    "Overcome Heights",
    "Rasta Str",
    "United Ave",
    "Victory Str",
  ],
  Xakabantu: ["Xakabantu"],
  Seawinds: [
    "Falcon Cres",
    "Finch Cres",
    "Flamingo Cres",
    "Francolin Cres",
    "Hornbill Cres",
    "Kamiesberg Rd",
    "Kingfisher Walk",
    "Military Rd",
    "Mossie Str",
    "Penguin Place",
    "Prince George Dr",
    "Puffin Cres",
    "Quail Cres",
    "Rooibekkie Str",
    "Saasveld Rd",
    "Seemeeu Cres",
    "Shrike Cres",
    "Spoonbill Rd",
    "St Boniface Rd",
    "St Catherine Rd",
    "St Edward Rd",
    "St Irene Rd",
    "St Laurence Cl",
    "St Linus Cl",
    "St Louis Cl",
    "St Lucina Cl",
    "St Lucy Cl",
    "St Luke Cl",
    "St Patrick Ave",
    "St Paul Circ",
    "St Peter Ave",
    "St Philip Str",
    "St Ralph Rd",
    "St Raymond Rd",
    "St Regis Rd",
    "St Richard Rd",
    "St Robert Lane",
    "St Robert Rd",
    "St Sebastian Str",
    "St Stanislas Str",
    "St Stephen Ave",
    "St Swithin Rd",
    "St Theresa Cres",
    "St Timothy Str",
    "St Titus Cres",
    "St Urban Cl",
    "St Urban Str",
    "St Ursula Str",
    "St Valentine Cl",
    "St Victor Cl",
    "St Vincent Lane",
    "St Wenceslas Str",
    "St Williams Cres",
    "St Williams Str",
    "St Winifred Str",
    "Stormvoel Sqre",
    "Sugarbird Cres",
    "Swallow Cres",
    "Swift Rd",
    "Woodpecker Str",
  ],
  Hillview: [
    "Amatola Way",
    "Aster Rd",
    "Bonteberg Rd",
    "Cederberg Rd",
    "China Town",
    "Dahliah Rd",
    "Daisy Rd",
    "Drakensberg Rd",
    "Gladiola Rd",
    "Hillview Ave",
    "Hillview Heights",
    "Kamiesberg",
    "Langeberg Str",
    "Lebombo Rd",
    "Lilly Way",
    "Magaliesberg Rd",
    "Maluti Str",
    "Military Rd",
    "Orchid Str",
    "Outeniqua Str",
    "Pilansberg",
    "Potberg Rd",
    "Protea Way",
    "Rose Str",
    "Sneeuberg",
    "Soutpansberg",
    "St Charles",
    "St Edward Ave",
    "St Irene",
    "St Paul",
    "St Swithin",
    "Sunflower Rd",
    "Tafelberg Rd",
    "Tsitsikamma Way",
    "Village Heights",
    "Winterberg Rd",
    "Witsenberg Rd",
  ],
  "Lavendar Hill": [
    "14th Ave",
    "Ashley Cres",
    "Blode Cl",
    "Blode Str",
    "Chapel Rd",
    "Clinton Rd",
    "Dennis Ave",
    "Depsiton Cres",
    "Eltister Rd",
    "Epsten Cres",
    "Epsten Hof",
    "Epsten Rd",
    "Erasmus Cl",
    "Grindal Ave",
    "Grindal Cl",
    "Grindal Cres",
    "Harley Str",
    "Hek Rd",
    "Hilary Cres",
    "Hilary Dr",
    "Hilary Way",
    "Ipsting Rd",
    "Joan Rd",
    "Military Rd",
    "Mirbey Rd",
    "Philmau Rd",
    "Prince George Dr",
    "Rifstone Rd",
    "Roos Rd",
    "Shepherd Rd",
    "Southern Hills Dr",
    "St Agatha Cres",
    "St Agatha Str",
    "St Agnes Str",
    "St Aidan Rd",
    "St Alban Str",
    "St Albert Rd",
    "St Alexander Circ",
    "St Alexander Rd",
    "St Alexis Rd",
    "St Alma Rd",
    "St Ambrose Circ",
    "St Andrew Rd",
    "St Anne Str",
    "St Anthony Rd",
    "St Augustine Rd",
    "St Barbara Rd",
    "St Barnabas Rd",
    "St Bartholomew Rd",
    "St Basil Str",
    "St Beatrice Str",
    "St Bede Str",
    "St Benedict Str",
    "St Bernard Cres",
    "St Blaise Cres",
    "St Blaise Str",
    "St Bonaface Rd",
    "St Bonaventure Rd",
    "St Brendan Rd",
    "St Bridget Str",
    "St Bruno Rd",
    "St Cecilia Str",
    "St Christopher Ave",
    "St Cosmos Rd",
    "St Esther Str",
    "St George Str",
    "St Johns Rd",
    "St Kilda Rd",
    "St Margaret Str",
    "St Marks Rd",
    "St Noah Str",
    "St Pauls Str",
    "St Ruth Str",
    "St Simon Str",
    "St Thomas Rd",
    "Stienie Rd",
    "Urfield Rd",
    "Welton Str",
    "Wichts Str",
    "Wilmar Str",
    "Yoksal Rd",
  ],
  "Cafda Village": [
    "11th Ave",
    "12th Ave",
    "Beethoven Rd",
    "Bernstein Rd",
    "Blagden Rd",
    "Chopin Str",
    "Elsie Manning Str",
    "Ensor Str",
    "Gordon Searle Clse",
    "Gordon Searle Str",
    "Ivo Chunnet Str",
    "Komlossy Str",
    "Nellie Spilhaus Str",
    "Oboe Str",
    "Peter Charles Str",
    "Prince George Dr",
    "Runge Str",
    "Schumann Str",
    "Tambourine Str",
    "Volksang Rd",
    "Walton Rd",
  ],
  "Coniston Park": [
    "Buttermere",
    "Coniston Ave",
    "Constance Rd",
    "Derwent Cres",
    "Florida Rd",
    "Frome Cres",
    "Garda Str",
    "Geneva Rd",
    "Lomond Cres",
    "Lucerne Cres",
    "Manitoba Rd",
    "Midmar Rd",
    "Military Rd",
    "Muritz Cls",
    "Muritz Pl",
    "Muritz Way",
    "St Lucia Cres",
    "Ullswater Rd",
    "Winnipeg Rd",
    "Yellowstone Cres",
  ],
  Retreat: [
    "1st Ave",
    "2nd Ave",
    "3rd Ave",
    "4th Ave",
    "5th Ave",
    "6th Ave",
    "7th Ave",
    "8th Ave",
    "9th Ave",
    "10th Ave",
    "Allenby Dr",
    "Ardleigh Cl",
    "Ardleigh Rd",
    "Ashville Cres",
    "Auriga Rd",
    "Austel Rd",
    "Bark Str",
    "Beethoven Rd",
    "Bernstein Rd",
    "Blagden Str",
    "Boundary Rd",
    "Canal Rd",
    "Canna Rd",
    "Cardross Grant Str",
    "Carter Rd",
    "Celie Rd",
    "Chad Rd",
    "Charity Rd",
    "Chipphillside Rd",
    "Chris Abraham Rd",
    "Church Rd",
    "Clivia Str",
    "Coller Rd",
    "Concert Blvrd",
    "Corona Rd",
    "Cowell Way",
    "Crest Way",
    "Edmonton Cl",
    "Edmonton Rd",
    "Erie Rd",
    "Evelyn Rd",
    "Felicia Str",
    "Flora Rd",
    "Fortuin Rd",
    "Fortuin Str",
    "Francke Str",
    "Frans Maroney Str",
    "Gail Rd",
    "Gazania Str",
    "Geneva Rd",
    "Golden Rd",
    "Grace Vulliamy Str",
    "Harmony Rd",
    "Hertslet Str",
    "Honeywell Rd",
    "Hudson Rd",
    "Hugo Naude Str",
    "Humility Cl",
    "Huntingdon Rd",
    "Hutchinson Rd",
    "Ivy Price Rd",
    "Joe Marks Blvrd",
    "Keysers Rd",
    "Kiran Rd",
    "Lakeview Dr",
    "Langevlei Rd",
    "Laura Rd",
    "Lensie Rd",
    "Lewin Rd",
    "Leytonstone Rd",
    "Liberty Rd",
    "Lily Rd",
    "Loch Rd",
    "Loman Rd",
    "Lucerne Rd",
    "Lullaby Ln",
    "Lyra Rd",
    "Mafeking Rd",
    "Magda Rd",
    "Main Rd",
    "Malawi Rd",
    "Manitoba Rd",
    "Metaal Str",
    "Metropolitan Rd",
    "Morris Way",
    "Myer Rd",
    "Nyasa Rd",
    "Ontario Rd",
    "Orrel Ave",
    "Pegasus Rd",
    "Petal Str",
    "Pieterse Cl",
    "Presence Rd",
    "Prince George Dr",
    "Princess Rd",
    "Rachel Dick Str",
    "Retreat Rd",
    "Robertson Ln",
    "Sasmeer Rd",
    "School Way",
    "Scottsville Rd",
    "Silver Rd",
    "Southgate Rd",
    "Spectra Rd",
    "Stamen Str",
    "Station Rd",
    "Sylvester Rd",
    "Taho Rd",
    "Tana Rd",
    "Taupo Cl",
    "Temperance Rd",
    "Tokai Rd Ext",
    "Tolerance Rd",
    "Toring Rd",
    "Tulip Rd",
    "Unity Rd",
    "Utah Cl",
    "Valley View Rd",
    "Van Rooyen Rd",
    "Vega Rd",
    "Velma Rd",
    "Victoria Rd",
    "Victory Rd",
    "Volta Rd",
    "Wals Ave",
    "Warren Cl",
    "Warrenside Rd",
    "Wessels Cres",
    "White Rd",
    "Wyehill Cl",
    "Wyehill Rd",
    "Yubel Rd",
    "Zwaans Rd",
  ],
  "Sheraton Park": [
    "Agate Clse",
    "Diamond Dr",
    "Emerald Cres",
    "Galilee Rd",
    "Garnet Cres",
    "Henley Rd",
    "Ivory Cl",
    "Jade Ln",
    "Jasper Str",
    "Military Rd",
    "Moonstone Cres",
    "Opal Ln",
    "Rosequarts Str",
    "Ruby Cres",
    "Steen Villa",
    "Topaz Str",
    "Turquoise Cres",
    "Zircon Circ",
  ],
  Steenberg: [
    "Aberfeldy Rd",
    "Abraham Ave",
    "Agate Cl",
    "Aiken Cl",
    "Aiken Rd",
    "Allenby Dr",
    "Amber Rd",
    "Ave Le Breton",
    "Bach Ave",
    "Banjo Rd",
    "Bassoon Str",
    "Bergen Rd",
    "Boland Way",
    "Botma Str",
    "Brahms Rd",
    "Britten Rd",
    "Bud Rd",
    "Buttermere Rd",
    "Carol Str",
    "Chard Rd",
    "Chasmante Cl",
    "Chevron Sq",
    "Chief Rd",
    "Chimes Str",
    "Choir Str",
    "Cone Rd",
    "Cradock Rd",
    "Crystal Rd",
    "Daisy Hill Rd",
    "Denyssen Rd",
    "Derwent Cres",
    "Diamond Dr",
    "Dune Rd",
    "Easson Rd",
    "Ebb Rd",
    "Elgar Str",
    "Farnmouth Rd",
    "Fauna Rd",
    "Flora Rd",
    "Flute Str",
    "Fontein Rd",
    "Frankfort Rd",
    "Franz Sq",
    "Frogmore Rd",
    "Galilee Cl",
    "Galilee Rd",
    "Garda Cl",
    "Geloof Str",
    "Gluck Str",
    "Goodman Rd",
    "Grens St",
    "Gumtree Rd",
    "Handel Str",
    "Harmonica Str",
    "Haydn Str",
    "Jamieson Cl",
    "Joe Marks Blvrd",
    "Joseph Andersen Str",
    "Julius Rd",
    "Klarinet Ave",
    "Klavier Str",
    "Kornet Aver",
    "Lake Rd",
    "Lute Ln",
    "Main Rd",
    "Mandoline Sq",
    "Melody Sq",
    "Military Rd",
    "Mozart Ave",
    "Nectar Rd",
    "Orchestra Str",
    "Pickerill Str",
    "Pollen Rd",
    "Powell Rd",
    "Prince George Dr",
    "Rankie Rd",
    "Ravel Str",
    "Regis Rd",
    "Rockhill Way",
    "Rosequartz Str",
    "Rossini Str",
    "Salem Rd",
    "Samba Cres",
    "Sand Olive Rd",
    "Saxo Str",
    "Serenade Rd",
    "Shell Rd",
    "Sibelius Ave",
    "Solo Str",
    "Sonata Str",
    "Squaw Rd",
    "Steenberg Cl",
    "Steenberg Rd",
    "Stingle Rd",
    "Strauss Ave",
    "Sullivan Rd",
    "Symphony Ave",
    "Tango Cres",
    "Tatum Rd",
    "Trompet Str",
    "Uithof Str",
    "Van Wyk Rd",
    "Verdi Str",
    "Viola Str",
    "Vrede Rd",
    "Wagner Way",
    "Wentzel Rd",
    "Woodwind Circ",
    "Zither Str",
  ],
  "Costa da Gama": ["Madeira Dr", "Minorca Ave", "Pembroke Pl", "The Breakers"],
  "Grassy Park": ["1st Ave", "Grendell Cres", "Ishack Rd", "Perth Rd", "Prince George Dr", "Stable Rd", "Zircon Circ"],
  Heideveld: ["Amber Str"],
  Khayelitsha: ["Vuyani Str"],
  "Marina da Gama": ["Shearwater Dr", "Promenade Rd"],
  Muizenberg: ["Hastings Rd", "Kensington Rd", "Ocean Breeze", "Ocean Villas"],
  "Pelican Park": ["Penguin Str"],
  Southfields: ["Princess Vuyo"],
  Strandfontein: ["Cabot Way", "Dennegeur Ave"],
};

/*{
  Cafda: ["12th Ave", "Komlossy", "Obeo Str"],
  ConistonPark: ["Coniston Court", "Frome Cres", "St Lucia Cres"],
  CostaDaGamma: ["Madeira Dr", "Minorca Rd", "Pembroke Pl", "The Breakers"],
  GrassyPark: ["1st Ave", "Grendell Cres", "Ishack Rd", "Perth Str", "Prince George Dr", "Stable Rd"],
  Heideveld: ["Amber Str"],
  Hillview: [
    "Aster Rd",
    "Bog Str",
    "Bonteberg Rd",
    "Cederberg Rd",
    "China Town",
    "Dahliah Rd",
    "Daisy Rd",
    "Darling Rd",
    "Depsiton Cres",
    "Drakensberg Rd",
    "Gladiola Rd",
    "Hillview Ave",
    "Hillview Heights",
    "Kamiesberg",
    "Langeberg Str",
    "Lebombo Rd",
    "Lilly Way",
    "Matola Rd",
    "Orchard Rd",
    "Outeniqua Str",
    "Pagoda Rd",
    "Phase 1",
    "Pilansberg",
    "Protea Way",
    "Rose Court",
    "Rose Str",
    "Sneeuberg",
    "Soutpansberg",
    "St Beatrice",
    "St Charles",
    "St Edwards",
    "St Irene",
    "St Orchard",
    "St Patricks",
    "St Paul",
    "St Swithin",
    "St Timothy",
    "St Vincent",
    "Sunflower Rd",
    "Tafelberg Rd",
    "Village Heights",
  ],
  Khayelitsha: ["Vuyani Str"],
  LavendarHill: [
    "Arundal Court",
    "Bartholomew Rd",
    "Chapel Rd",
    "Depsiton Cres",
    "Dover Court",
    "Elister",
    "Epston Cres",
    "Epston Rd",
    "Grindal Ave",
    "Hillary Dr",
    "Langeberg Rd",
    "Lebombo Str",
    "Maluti Str",
    "Parkin Court",
    "Pontac Court",
    "St Barbara Rd",
    "St Barnard",
    "St Benedict Str",
    "St Blaze Str",
    "St Paul Circ",
    "St Thomas Str",
    "Stone Court",
    "Stormvoel Rd",
    "Stuckeris Close",
    "Urfield Rd",
    "Van der Leur Court",
    "Village Heights",
    "Welton Rd",
  ],
  Leeds: ["Philbert Str"],
  MarinaDaGamma: ["Shearwater Dr"],
  MontaguV: [
    "St Agatha Rd",
    "St Ambrose",
    "St Augustine Rd",
    "St Barbara Rd",
    "St Barnabas",
    "St Bartholomew",
    "St Basil Str",
    "St Bede Str",
    "St Benedict Str",
    "St Bernard Cres",
    "St Blaize Str",
    "St Brendan Rd",
    "St Breda Str",
    "St Bridget",
    "St Cecilia",
    "St Christopher Rd",
    "St Paulse Circ",
    "St Thomas Str",
    "St Urban",
    "St Victor",
  ],
  Muizenberg: ["Hastings Rd", "Kensington Rd", "Ocean Breeze", "Ocean Villas", "Pambrook Pl", "Promenade Rd", "Shearwater Dr"],
  OvercomeHeights: [
    "7th Avenue",
    "Aster Rd",
    "Blaizer Str",
    "Bree Str",
    "Errol Str",
    "Freedom Rd",
    "Ghetto",
    "Italyfield",
    "Kennedy Rd",
    "Liberty Rd",
    "Masakoni Rd",
    "Mercy Rd",
    "Mountain Rd",
    "Phase 1",
    "Rasta Str",
    "United Ave",
    "Victory Str",
  ],
  PelicanPark: ["Penguin Str"],
  Retreat: [
    "3rdAve",
    "11 Ave",
    "12th Ave",
    "Brahms Rd",
    "Chad Rd",
    "Consort Rd",
    "Elgar Str",
    "Hugo Naude",
    "Komlossy Str",
    "Military Rd",
    "Oboe Str",
    "Runge Str",
    "Taupo Cl",
    "Tambourine Str",
    "Walton Rd",
  ],
  Seawinds: [
    "Falcon Str",
    "Finch Cres",
    "Francolin Str",
    "Kingfisher Rd",
    "Military Heights",
    "Orchard Str",
    "Penguin Str",
    "Puffin Rd",
    "Rooibekkie Str",
    "Seemeeu Circ",
    "Shrike Rd",
    "Sonata Str",
    "Spoonbill Cres",
    "St Beatrice",
    "St Edwards",
    "St Lewis Cl",
    "St Luke Cl",
    "St Patrick Ave",
    "St Peters",
    "St Phillips",
    "St Raymond Rd",
    "St Regis Str",
    "St Richard",
    "St Roberts",
    "St Sebastian",
    "St Stanislas",
    "St Stephens",
    "St Theresa",
    "St Theresa Cres",
    "St Timothy",
    "St Titus",
    "St Titus Cres",
    "St Urban",
    "St Urban Cl",
    "St Ursula",
    "St Wenceslas",
    "St William Cres",
    "Stormvoel Rd",
    "Sugarbird Str",
    "Swallow Str",
    "Swift Rd",
    "Woodpecker Str",
  ],
  Seekoeivlei: ["Victoria Rd"],
  StRuth: ["Cuban Heights"],
  Steenberg: [
    "Amber Rd",
    "Botma Str",
    "Craddock Rd",
    "Crystal Rd",
    "Flute Str",
    "Fontein Rd",
    "Grensweg",
    "Klavier Ln",
    "Orchestra Rd",
    "Rose Quartz",
    "Solo Str",
    "Squaw Rd",
    "Steen Villa",
    "Symphony Ave",
    "Turquoise Cres",
    "Zircon Circ",
  ],
  Strandfontein: ["Cabot Way", "Dennegeur"],
  Southfield: ["Princess Vuyo"],
  Vrygrond: [
    "Apple Cl",
    "Apple Rd",
    "Berg Str",
    "Berry Cl",
    "Berry Rd",
    "Church Circ",
    "Classen Rd",
    "Dassie Cl",
    "Dassie Rd",
    "Davids Rd",
    "Dawn Rd",
    "Disa Cl",
    "Disa Rd",
    "Doring Cl",
    "Doring Rd",
    "Drury Cl",
    "Drury Rd",
    "Fredericks Cl",
    "Fredericks Rd",
    "Harmony Cl",
    "Harmony Rd",
    "Jappie Rd",
    "Jonathan Rd",
    "Neville Riley Rd",
    "Orange Cl",
    "Orange Rd",
    "Peach Cl",
    "Peach Rd",
    "Philemon Rd",
    "Plum Str",
    "Thys Witbooi Cl",
    "Thys Witbooi Rd",
    "Trevor Siljeur Cl",
    "Trevor Siljeur Rd",
    "Vrygrond Ave",
    "Vuyo Cl",
    "Vuyo Rd",
  ],
};*/
