export const areaOptions = [
  "All areas",
  "Vrygrond",
  "Overcome Heights",
  "Xakabantu",
  "Seawinds",
  "Hillview",
  "Lavendar Hill",
  "Cafda Village",
  "Coniston Park",
  "Retreat",
  "Sheraton Park",
  "Steenberg",
  "Costa da Gama",
  "Grassy Park",
  "Heideveld",
  "Khayelitsha",
  "Marina da Gama",
  "Muizenberg",
  "Pelican Park",
  "Southfields",
  "Strandfontein",
];
/*export const areaOptions = [
  "Cafda",
  "Coniston Park",
  "Costa da Gamma",
  "Grassy Park",
  "Heideveld",
  "Hillview",
  "Khayelitsha",
  "Lavendar Hill",
  "Leeds",
  "Marina Da Gamma",
  "Montagu V",
  "Muizenberg",
  "Overcome Heights",
  "Pelican Park",
  "Seawinds",
  "Seekoei vlei",
  "St Ruth",
  "Steenberg",
  "Strandfontein",
  "Southfield",
  "Vrygrond",
];*/
