export type AreaStreetMapping = Record<string, string[]>;

export const areaStreetMapping: AreaStreetMapping = {
  Cafda: ["12th Ave", "Komlossy", "Obeo Str"],
  ConistonPark: ["Coniston Court", "Frome Cres", "St Lucia Cres"],
  CostaDaGamma: ["Madeira Dr", "Minorca Rd", "Pembroke Pl", "The Breakers"],
  GrassyPark: ["1st Ave", "Grendell Cres", "Ishack Rd", "Perth Str", "Prince George Dr", "Stable Rd"],
  Heideveld: ["Amber Str"],
  Hillview: [
    "Aster Rd",
    "Bog Str",
    "Bonteberg Rd",
    "Cederberg Rd",
    "China Town",
    "Dahliah Rd",
    "Daisy Rd",
    "Darling Rd",
    "Depsiton Cres",
    "Drakensberg Rd",
    "Gladiola Rd",
    "Hillview Ave",
    "Hillview Heights",
    "Kamiesberg",
    "Langeberg Str",
    "Lebombo Rd",
    "Lilly Way",
    "Matola Rd",
    "Orchard Rd",
    "Outeniqua Str",
    "Pagoda Rd",
    "Phase 1",
    "Pilansberg",
    "Protea Way",
    "Rose Court",
    "Rose Str",
    "Sneeuberg",
    "Soutpansberg",
    "St Beatrice",
    "St Charles",
    "St Edwards",
    "St Irene",
    "St Orchard",
    "St Patricks",
    "St Paul",
    "St Swithin",
    "St Timothy",
    "St Vincent",
    "Sunflower Rd",
    "Tafelberg Rd",
    "Village Heights",
  ],
  Khayelitsha: ["Vuyani Str"],
  LavendarHill: [
    "Arundal Court",
    "Bartholomew Rd",
    "Chapel Rd",
    "Depsiton Cres",
    "Dover Court",
    "Elister",
    "Epston Cres",
    "Epston Rd",
    "Grindal Ave",
    "Hillary Dr",
    "Langeberg Rd",
    "Lebombo Str",
    "Maluti Str",
    "Parkin Court",
    "Pontac Court",
    "St Barbara Rd",
    "St Barnard",
    "St Benedict Str",
    "St Blaze Str",
    "St Paul Circ",
    "St Thomas Str",
    "Stone Court",
    "Stormvoel Rd",
    "Stuckeris Close",
    "Urfield Rd",
    "Van der Leur Court",
    "Village Heights",
    "Welton Rd",
  ],
  Leeds: ["Philbert Str"],
  MarinaDaGamma: ["Shearwater Dr"],
  MontaguV: [
    "St Agatha Rd",
    "St Ambrose",
    "St Augustine Rd",
    "St Barbara Rd",
    "St Barnabas",
    "St Bartholomew",
    "St Basil Str",
    "St Bede Str",
    "St Benedict Str",
    "St Bernard Cres",
    "St Blaize Str",
    "St Brendan Rd",
    "St Breda Str",
    "St Bridget",
    "St Cecilia",
    "St Christopher Rd",
    "St Paulse Circ",
    "St Thomas Str",
    "St Urban",
    "St Victor",
  ],
  Muizenberg: ["Hastings Rd", "Kensington Rd", "Ocean Breeze", "Ocean Villas", "Pambrook Pl", "Promenade Rd", "Shearwater Dr"],
  OvercomeHeights: [
    "7th Avenue",
    "Aster Rd",
    "Blaizer Str",
    "Bree Str",
    "Errol Str",
    "Freedom Rd",
    "Ghetto",
    "Italyfield",
    "Kennedy Rd",
    "Liberty Rd",
    "Masakoni Rd",
    "Mercy Rd",
    "Mountain Rd",
    "Phase 1",
    "Rasta Str",
    "United Ave",
    "Victory Str",
  ],
  PelicanPark: ["Penguin Str"],
  Retreat: [
    "3rdAve",
    "11 Ave",
    "12th Ave",
    "Brahms Rd",
    "Chad Rd",
    "Consort Rd",
    "Elgar Str",
    "Hugo Naude",
    "Komlossy Str",
    "Military Rd",
    "Oboe Str",
    "Runge Str",
    "Taupo Cl",
    "Tambourine Str",
    "Walton Rd",
  ],
  Seawinds: [
    "Falcon Str",
    "Finch Cres",
    "Francolin Str",
    "Kingfisher Rd",
    "Military Heights",
    "Orchard Str",
    "Penguin Str",
    "Puffin Rd",
    "Rooibekkie Str",
    "Seemeeu Circ",
    "Shrike Rd",
    "Sonata Str",
    "Spoonbill Cres",
    "St Beatrice",
    "St Edwards",
    "St Lewis Cl",
    "St Luke Cl",
    "St Patrick Ave",
    "St Peters",
    "St Phillips",
    "St Raymond Rd",
    "St Regis Str",
    "St Richard",
    "St Roberts",
    "St Sebastian",
    "St Stanislas",
    "St Stephens",
    "St Theresa",
    "St Theresa Cres",
    "St Timothy",
    "St Titus",
    "St Titus Cres",
    "St Urban",
    "St Urban Cl",
    "St Ursula",
    "St Wenceslas",
    "St William Cres",
    "Stormvoel Rd",
    "Sugarbird Str",
    "Swallow Str",
    "Swift Rd",
    "Woodpecker Str",
  ],
  Seekoeivlei: ["Victoria Rd"],
  StRuth: ["Cuban Heights"],
  Steenberg: [
    "Amber Rd",
    "Botma Str",
    "Craddock Rd",
    "Crystal Rd",
    "Flute Str",
    "Fontein Rd",
    "Grensweg",
    "Klavier Ln",
    "Orchestra Rd",
    "Rose Quartz",
    "Solo Str",
    "Squaw Rd",
    "Steen Villa",
    "Symphony Ave",
    "Turquoise Cres",
    "Zircon Circ",
  ],
  Strandfontein: ["Cabot Way", "Dennegeur"],
  Southfield: ["Princess Vuyo"],
  Vrygrond: [
    "Apple Cl",
    "Apple Rd",
    "Berg Str",
    "Berry Cl",
    "Berry Rd",
    "Church Circ",
    "Classen Rd",
    "Dassie Cl",
    "Dassie Rd",
    "Davids Rd",
    "Dawn Rd",
    "Disa Cl",
    "Disa Rd",
    "Doring Cl",
    "Doring Rd",
    "Drury Cl",
    "Drury Rd",
    "Fredericks Cl",
    "Fredericks Rd",
    "Harmony Cl",
    "Harmony Rd",
    "Jappie Rd",
    "Jonathan Rd",
    "Neville Riley Rd",
    "Orange Cl",
    "Orange Rd",
    "Peach Cl",
    "Peach Rd",
    "Philemon Rd",
    "Plum Str",
    "Thys Witbooi Cl",
    "Thys Witbooi Rd",
    "Trevor Siljeur Cl",
    "Trevor Siljeur Rd",
    "Vrygrond Ave",
    "Vuyo Cl",
    "Vuyo Rd",
  ],
};
