export const areaOptions = [
  "Cafda",
  "Coniston Park",
  "Costa da Gamma",
  "Grassy Park",
  "Heideveld",
  "Hillview",
  "Khayelitsha",
  "Lavendar Hill",
  "Leeds",
  "Marina Da Gamma",
  "Montagu V",
  "Muizenberg",
  "Overcome Heights",
  "Pelican Park",
  "Seawinds",
  "Seekoei vlei",
  "St Ruth",
  "Steenberg",
  "Strandfontein",
  "Southfield",
  "Vrygrond",
];
